package sectionone;
//import java.io.IOException;
public class TRYY extends Try2{
	static int n=10;
	
		   public static void main(String[] args) {
			  
			   m1();
		   }
		   public static void m1()  {
			   System.out.println("mi stats");
			   m2();
		   }
		   public static void m2()  {
			   try { 
				   
				   throw new Exception("not able to");
			   
		   }
			   catch (Exception a1) {
				   System.out.println(a1.getMessage());
			   }
		   }
}
				   
	
				
	